### ISSUE TITLE
SALs: process (local and remote executors based on fabric)

### ISSUE THREAD

**Issue by abom** [js-next/js-ng#1]
TBD:

http://www.fabfile.org/

**Comment by Pishoy** [comment]
I can not find it, should it be like j.sals.fabric or something else?

![image](https://user-images.githubusercontent.com/21987477/85948253-26575000-b950-11ea-9f59-d790f275dae1.png)

**Comment by Pishoy** [comment]
j.sals.process.execute docs not showing it is remote 

```
JS-NG> j.sals.process.execute( 

execute(cmd, showout=False, cwd=None, shell='/bin/bash', timeout=600, asynchronous=False, env=None, replace_env=False, die=False) 
 
execute a command. 
 
accepts command as a list too, with auto-escaping. 
 
Arguments: 
    cmd (str or list): command to be executed, e.g. `"ls -la"` or `["ls", "-la"] 
 
Keyword Arguments: 
    showout (bool): show stdout of the command (default: False) 
    cwd (str): specify a working directory for the command (default: None)    
```

**Comment by xmonader** [comment]
https://threefoldtech.github.io/js-ng/wiki/#/./executors

**Comment by Pishoy** [comment]
Thanks , Please add a more details docs for remote executor 

![image](https://user-images.githubusercontent.com/21987477/85950818-5e19c400-b95f-11ea-98d4-846a2751b555.png)

**Comment by xmonader** [comment]
> Thanks , Please add a more details docs for remote executor
> 
> ![image](https://user-images.githubusercontent.com/21987477/85950818-5e19c400-b95f-11ea-98d4-846a2751b555.png)

can you please open a feature request for that?
