### ISSUE TITLE
Gedis server needs away to start/stop and create 

### ISSUE THREAD

**Issue by 0xIslamTaha** [js-next/js-ng#126]
I can see that the way we are using Gedis needs some enhancments as we can only use `new_server` method. 

- create an instance
- start server with a specific port
- start server in the background

**Comment by RafyAmgadBenjamin** [comment]
### verified 

#### Get instance and start using the default port
```
 t = j.servers.gedis.get("test") 
t.start()     
```
![image](https://user-images.githubusercontent.com/46320202/85950302-5147a100-b95c-11ea-870c-d573226d754b.png)

#### Stop Gedis server
```
t.stop()
```
![image](https://user-images.githubusercontent.com/46320202/85950457-1a25bf80-b95d-11ea-8286-4b6614072f7d.png)

#### Get instance and start using a different port
```
t = j.servers.gedis.new("testing",port=1500)
t.start()
```
![image](https://user-images.githubusercontent.com/46320202/85950514-80124700-b95d-11ea-8b40-3703379ae0d8.png)
