### ISSUE TITLE
basic requirements specs

### ISSUE THREAD

**Issue by despiegk** [js-next/js-ng#129]
## types / baseclasses

- clean on each type, to deal with magic things like +1h, -2d, for time or any other automatic conversions
- hierarchical objects 
    - serialize object from a certain point down
- triggers
    - on field changes or pre & post serialization

## container mgmt

- what we use from jsx tool as today

## user experience

- nice shell (not ipython)
- we will not create any command line any more
- the starting point is a shell (our shell) in python in which we can do all
- hide all developer hooks by default (_, __, classes, ...)

## compatibility

- pyinstall
- windows, linux, osx for the core features (enough to install container with TFGrid SDK)

**Comment by xmonader** [comment]
will do pyinstall in alpha2 and same for container mgmt
