### ISSUE TITLE
add more fields to our baseclasses using data/types.py 

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#140]
port more advanced fields like tel, ipaddress,.. etc from types into fields.py file

**Comment by RafyAmgadBenjamin** [comment]
### Add the Email, path, URL, tel, IP address , DateTime, date, time, duration types to our fields

commits
https://github.com/js-next/js-ng/commit/6922d2679d76ba7e975101f1d9a016c7c249c3b6
https://github.com/js-next/js-ng/commit/6502a752b7d013708c1de04afd88f6a27c2def1e
https://github.com/js-next/js-ng/commit/89ce048be13080f27912f48d80c97df4a139fd56
https://github.com/js-next/js-ng/commit/1d0a0e665b9f83e70f7c5772feefc4ffe573cd4e
https://github.com/js-next/js-ng/commit/a0885c03e52b412c05b253ba70db0408e96ddfdb

**Comment by RafyAmgadBenjamin** [comment]
Fixing some bugs and adding some enhancements
commit:
https://github.com/js-next/js-ng/pull/170/commits/102166da426e1cc71e9cf34662711663de86a72c

**Comment by RafyAmgadBenjamin** [comment]
add tests to our fields and update the error message
commit
https://github.com/js-next/js-ng/pull/170/commits/f40d8be58bcdf9f2756fb20122db6c259bbfd615
