### ISSUE TITLE
add countries helper

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#144]
add pycountriy

**Comment by xmonader** [comment]
https://github.com/js-next/js-ng/commit/7524facdc5748e348491453c78b8a0104eb8daf2

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-06-28 12-19-19](https://user-images.githubusercontent.com/26298009/85944717-3ca5e180-b939-11ea-81cf-421fa310e357.png)
