### ISSUE TITLE
repo mgmt

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#166]
- CI
- pre-commit hooks
- Dockerfile

**Comment by xmonader** [comment]
all three are done.

**Comment by xmonader** [comment]
image published as threefoldtech/js-ng

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/85943460-8938ef00-b930-11ea-9fc2-b28f4d75a172.png)
