### ISSUE TITLE
Auto-completion fails to list sub-modules in js-ext

### ISSUE THREAD

**Issue by abom** [js-next/js-ng#18]
All modules are loaded, but only [extension](https://github.com/js-next/js-ext) modules are listed by auto-completion in shell.
It needs to be investigated and tested on our jsng shell.

**Comment by xmonader** [comment]
fixed

**Comment by Pishoy** [comment]
verified 

![image](https://user-images.githubusercontent.com/21987477/85705380-71b7f700-b6e1-11ea-9652-4d39db60d950.png)
