### ISSUE TITLE
baseclasses triggers and autocasting

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#184]
let's make sure we treat the users gently if they pass something like `on` or `t`, `y`, `yes`'.. to boolean field and treat it as True and `f`, `no`, `off` as False

- [x] expose triggers (via events)
- [ ] improve docs

**Comment by abom** [comment]
Added events (for triggers).

**Comment by abom** [comment]
For fields, we now support this auto-casting.

**Comment by ashraffouda** [comment]
verifying

**Comment by ashraffouda** [comment]
supported types 
![Screenshot from 2020-07-01 15-11-02](https://user-images.githubusercontent.com/1689456/86247745-35870980-bbad-11ea-9a41-46ef56796281.png)
