### ISSUE TITLE
update fs docs

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#188]
General docs in the fs module
show examples
show what can be done with very minimal code

**Comment by RafyAmgadBenjamin** [comment]
I have added examples and update the docs
except
* rmtree needs python 3.7
* copy_stat
* lchmod  got error```not available on this system```
* last four functions as there were already docs with example

commit 
https://github.com/js-next/js-ng/commit/52bbccf02305b1d0d6500c841b41f90149abac01

**Comment by Pishoy** [comment]
can not verify till now waiting https://github.com/threefoldtech/js-sdk/issues/107

![image](https://user-images.githubusercontent.com/21987477/85713608-d414f580-b6e9-11ea-8e18-8a351e68731b.png)

**Comment by Pishoy** [comment]
works a below 
![image](https://user-images.githubusercontent.com/21987477/85714623-e6436380-b6ea-11ea-8911-6c1094f66266.png)
