### ISSUE TITLE
autocompletion and docstrings

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#192]
can't complete on j
can't see docstrings

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/78954394-5bd06800-7adc-11ea-994b-543482de64af.png)
![image](https://user-images.githubusercontent.com/64129/78954401-5ecb5880-7adc-11ea-9ce5-9f8d44c0723e.png)

fixed in ecfe3f795692c65c17fd0374c374500cb68b21a3

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
