### ISSUE TITLE
Use recent version of ptpython and make sure shell config works too

### ISSUE THREAD

**Issue by abom** [js-next/js-ng#197]
Use a recent version of `ptpython` and make sure that our custom monkey-patching works.

Maybe get rid of eval too, and may support:
- [x] Coloring according to type (see [get_completions](https://github.com/prompt-toolkit/ptpython/blob/ee551a37fcc9f02fb9b29070460ab26364adaad9/ptpython/completer.py#L120) and [Script.complete](https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Script.complete) of `jedi`, as the later should return `Completion` with the type and is used by the earlier).
- [x] Filtering on prefixes with sorting, like `_`, '__`, lower case letters...

**Comment by abom** [comment]
https://github.com/js-next/js-ng/commit/731a67653c32ffbcd7b3844fb3222234cfb467ce

**Comment by siddiquagig** [comment]
Verified
