### ISSUE TITLE
check mybinder for sharing notebooks 

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#198]
https://mybinder.org looks powerful and might be useful to showcase the framework too

**Comment by RafyAmgadBenjamin** [comment]
- create a dockerfile used by binder for configuration
- update the image already created for jsng to be able to be used by the new dockerfile so binder will be able to use it.

**Comment by RafyAmgadBenjamin** [comment]
- I am worried about binder as it sometimes misbehave,I have added examples but It can only just show  three of them
![image](https://user-images.githubusercontent.com/46320202/80305993-b1855f80-87c0-11ea-822a-b94a866ad68c.png)
![image](https://user-images.githubusercontent.com/46320202/80305997-b518e680-87c0-11ea-9937-8d5cc79397db.png)

and sometimes it shows all the examples

- sometimes it builds and gives a mistake that he can not find the branch I am using  
![image](https://user-images.githubusercontent.com/46320202/80306019-e2fe2b00-87c0-11ea-8d21-5578b00b7bb6.png)
and out of nothing after rebuilding again it works well

**Comment by RafyAmgadBenjamin** [comment]
- I have added more examples to notebook 
PR 
https://github.com/js-next/js-ng/pull/234

**Comment by RafyAmgadBenjamin** [comment]
I have added more examples including  dirs, config , exceptions (that shows better exceptions), and more on data like fake, platform, random_names, terminaltables, proccess , dnstool, http tool


#### commit
ea026c1be80fbd55f9633b15710e694232f5a874

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
