### ISSUE TITLE
SALs

### ISSUE THREAD

**Issue by abom** [js-next/js-ng#2]
We should implement/port some important SALs from current jsx:

- [x] [fs](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/sal/fs) **Awady/Kiro**
- [x] [hostfile](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/sal/hostfile) **Abdelaziz**
- [x] [executors](https://github.com/js-next/js-ng/issues/1)

**Comment by Omarabdul3ziz** [comment]
this is the code I wrote for the hosts file issue: https://github.com/js-next/js-ng/pull/30/files
would it be better if I use "python-hosts" lib ?? : https://github.com/jonhadfield/python-hosts

**Comment by Pishoy** [comment]
verified 

```
JS-NG> j.sals.hostsfile.HostsFile
```
