### ISSUE TITLE
dashboard solution

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#216]
- search for dashboards 
- suggest options
- settle on one
- validate webix theming

**Comment by RafyAmgadBenjamin** [comment]
This website has many free templates using Vue.js
https://colorlib.com/wp/free-vuejs-admin-template/

Another option
https://vuejsadmin.com/product/vue-material-admin/
https://preview.vuejsadmin.com/item/vue-material-admin

**Comment by xmonader** [comment]
https://github.com/js-next/js-sdk/issues/2 to be part of sdk project instead

**Comment by hossnys** [comment]
verified
