### ISSUE TITLE
more fields required

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#245]
- [x] Guid
- [x] Port
- [x] IPAddress (v4, v6)
- [x] IPRange
- [x] Bytes
- [x] Json

**Comment by xmonader** [comment]
@m-motawea please add more fields if needed for sal zos + chatflows

**Comment by RafyAmgadBenjamin** [comment]
I am verifying this

**Comment by RafyAmgadBenjamin** [comment]
#### validate Guid
```
field = j.core.base.fields.GUID() 
field.default = "3297F0F2-35D3-4231-919D-1CFCF4035975" 
field.validate("3297F0F2-35D3-4231-919D-1CFCF4035975") 
```

```
field.validate("test") 
```
it raises exception
![image](https://user-images.githubusercontent.com/46320202/86533275-4ea2f980-bed0-11ea-8f4f-93666bed21c9.png)
