### ISSUE TITLE
make sure threebot server packages are tracked [development_threebot]

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#259]
- Threebot server packages are loaded in memory it will volatile on restart
- make sure to use config manager to save them

- README for the server: https://github.com/js-next/js-ng/blob/development_threebot/docs/wiki/threebot.md

**Comment by waleedhammam** [comment]
**Commit**: https://github.com/js-next/js-ng/commit/68d8b59fe0d7beae9a376ee15f8469e0a14d2d60

**Changelog**:
- Make packagemanager class as a factory
- Each threebot (if there are many) can have it's own package manager by the samename
- save packages to config manager after adding it

![Screenshot from 2020-05-31 18-58-56](https://user-images.githubusercontent.com/10658229/83358040-e614aa00-a370-11ea-8948-fb0a1d198a37.png)

**Comment by AhmedSa-mir** [comment]
verifying

**Comment by AhmedSa-mir** [comment]
verified.
