### ISSUE TITLE
autocomplete in shell should highlight the selected option

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#260]
when pressing tab it moves to the next option but don't highlight it

![Screenshot from 2020-05-31 13-55-53](https://user-images.githubusercontent.com/10658229/83351690-86090e00-a346-11ea-9aa5-df405c1f2769.png)

can be something like to determine the current option ?
![Screenshot from 2020-05-31 13-57-57](https://user-images.githubusercontent.com/10658229/83351722-c6688c00-a346-11ea-88e3-bc657dbf85d6.png)

**Comment by abom** [comment]
https://github.com/js-next/js-ng/commit/7755edd33e70c7f0f47f744d552063c354bcbaff

**Comment by waleedhammam** [comment]
Thanks ! [Screenshot from 2020-06-03 23-52-57](https://user-images.githubusercontent.com/10658229/83692996-621f2400-a5f5-11ea-9d19-75fd10ac4bd6.png)

**Comment by hossnys** [comment]
verified 
![Screenshot from 2020-06-22 18-48-26](https://user-images.githubusercontent.com/26298009/85313761-cdec0280-b4b8-11ea-92af-47fe1c9a8652.png)
