### ISSUE TITLE
create nginx tool 

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#264]
- create a tool for nginx for 
install method (to install nginx and certbot: https://github.com/js-next/js-ng/blob/59013cd1575dd0c2b0225813b9fdbc8e1ea09574/docs/wiki/research/nginx_ssl.md)
start
stop
reload (sighub)

- to start nginx `sudo nginx -c ~/sandbox/cfg/nginx/main/nginx.conf`

- suggested configurations to use in config manager: (name, configs path)

**Comment by BolaNasr** [comment]
PR : https://github.com/js-next/js-ng/pull/278

**Comment by Pishoy** [comment]
can not find install method 

![image](https://user-images.githubusercontent.com/21987477/85944620-70343c00-b938-11ea-9360-d07a6a394d40.png)

**Comment by AhmedSa-mir** [comment]
Install method is not needed now and removed in https://github.com/threefoldtech/js-sdk/pull/95
