### ISSUE TITLE
Error on executing `j.core.executors.run_local("uname", echo=False)` command in jsng

### ISSUE THREAD

**Issue by AhmedSa-mir** [js-next/js-ng#266]
Error on executing `j.core.executors.run_local("uname", echo=False)` command in jsng

![Screenshot from 2020-06-01 17-14-09](https://user-images.githubusercontent.com/18093386/83423558-6f88b280-a42b-11ea-9f58-9a016ec1e5e3.png)
![Screenshot from 2020-06-01 17-14-42](https://user-images.githubusercontent.com/18093386/83423578-76afc080-a42b-11ea-8ffd-41ebb0817931.png)

**Comment by waleedhammam** [comment]
also when exposing port 443 https://gist.github.com/waleedhammam/b645449a9e65e185d5b7bf69871f9b6d

**Comment by waleedhammam** [comment]
works as expected
