### ISSUE TITLE
startupcmds requires tmux to be open

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#270]
```
cmd = j.tools.startupcmd.get("hamada")
cmd.start_cmd = "nginx -c ~/sandbox/cfg/nginx/main.conf"
cmd.start()
```

![Screenshot from 2020-06-02 18-03-25](https://user-images.githubusercontent.com/10658229/83542708-9ca49600-a4fb-11ea-9f48-2db948bd3e13.png)

it works without problems when i manually start tmux

**Comment by BolaNasr** [comment]
PR : fix this issue at this PR https://github.com/js-next/js-ng/pull/278

**Comment by hossnys** [comment]
verified
