### ISSUE TITLE
more helpers required in sal/process

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#287]
- [x] get all processes
- [x] get all occupied ports with process pid
 
all extra functionalities needed for [health actor](
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/admin/actors/health.py)

**Comment by abom** [comment]
added at: https://github.com/js-next/js-ng/commit/6d9c9e04ba980297427713f281e075f04774bc90.

**Comment by AhmedSa-mir** [comment]
verifying

**Comment by AhmedSa-mir** [comment]
verified.
