### ISSUE TITLE
md_show cause greenlet to stuck and doesn't go to next step

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#299]
![Screenshot from 2020-06-09 10-38-09](https://user-images.githubusercontent.com/10658229/84128520-fdbef300-aa40-11ea-83b8-a8b59a4a9364.png)

**Comment by waleedhammam** [comment]
example from bar package
![Screenshot from 2020-06-09 11-08-20](https://user-images.githubusercontent.com/10658229/84128927-8b024780-aa41-11ea-96aa-b16cefddb0e9.png)

**Comment by waleedhammam** [comment]
works now, thanks

**Comment by hossnys** [comment]
verified
