### ISSUE TITLE
error with validating ip 

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#300]
![Screenshot from 2020-06-09 11-02-34](https://user-images.githubusercontent.com/10658229/84130875-18df3200-aa44-11ea-9caf-7e174ed12d88.png)

**Comment by waleedhammam** [comment]
commit: https://github.com/js-next/js-ng/commit/291f0cb83ce131246199e33127255560eb0e74bc

**Comment by Pishoy** [comment]
chat flow works fine and that model already used
