### ISSUE TITLE
Data layer

### ISSUE THREAD

**Issue by abom** [js-next/js-ng#5]
For the data layer where, the following need to be implemented/ported:

- [x] [hashing](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/hash) **Omar**
- [x] [encryption](https://github.com/js-next/js-ng/issues/3) **awady**
- [x] [lru cache](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/cachelru) (use [functools](https://docs.python.org/3/library/functools.html#functools.lru_cache))
- [x] [serializers](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/serializers) **Omar/Group**
- [x] [ini files](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/inifile) **Abdelaziz**
- [x] [id generators](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/idgenerator) **Kiro**
- [x] [random names](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/random_names) **Krio**
- [x] [tarfile](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/tarfile) **Abdelaziz/Omar**
- [x] [zipfile](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/zip) **Abdelaziz/Omar**
- [x] [datetime](https://github.com/js-next/js-ng/issues/4) **Awady**
- [x] [tree](https://github.com/threefoldtech/jumpscaleX/tree/master/Jumpscale/data/treemanager) **Awady**

**Comment by OmarElawady** [comment]
I created a draft pull request for the tree manager:
https://github.com/js-next/js-ng/pull/33
My initial thought about the implementation is as following:
1. TreeManager contains a root node and delegates most of the work to TreeItem objects.
2. Every node has a name. The names allows duplicates but not in the same level (The children of any node must have distinct names).
3. Search methods allows searching by name, value, or by providing a predicate that receives a TreeItem and returns a boolean. Search methods always return a list of filtered TreeItems.
4. Path are used to get node or to add a new node (that's why names must be unique for the same level).

**Comment by OmarElawady** [comment]
Implemented the methods. I have two questions addressed as a comments in the code:
1. In add_node_by_path if a node is not found while traversing the path. Should I create it, throw an exception or ignore the node addition?
2. If a node is requested to add a child with a name that is already taken by another child, Should I override it, throw an exception or ignore the child node addition?

I also added a sample of how one might use the Tree class as a file manager.

**Comment by abom** [comment]
@OmarElawady 

1. You should create it.
2. Throw an exception that a`Node` with the same name exists across the path in the same level (make it a custom exception).

**Comment by OmarElawady** [comment]
treemanager merged. Now working on rsync.

**Comment by xmonader** [comment]
https://github.com/js-next/js-ng/commit/2cf42d0129065005002b1322a059fa44fa00d878 add lru_cache

**Comment by RafyAmgadBenjamin** [comment]
I will verify this

**Comment by RafyAmgadBenjamin** [comment]
# Hashing 
```
JS-NG> j.data.hash.sha256("abc")                                                                                                                                             
'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'

JS-NG> j.data.hash.md5("abc")                                                                                                                                                
'900150983cd24fb0d6963f7d28e17f72'

JS-NG> j.data.hash.blake2b("abc")                                                                                                                                            
'ba80a53f981c4d0d6a2797b69f12f6e94c212f14685ac4b74b12bb6fdbffa2d17d87c5392aab792dc252d5de4533cc9518d38aa8dbf1925ab92386edd4009923'

JS-NG> j.data.hash.shake_128("abc")                                                                                                                                          
'5881092dd818bf5cf8a3ddb793fbcba7'

JS-NG> j.data.hash.sha1("abc")                                                                                                                                               
'a9993e364706816aba3e25717850c26c9cd0d89d'
```

**Comment by RafyAmgadBenjamin** [comment]
#### Serializers in toml crashed
```
JS-NG> j.data.serializers.toml.dumps("title = 'TOML Example'") 
```
![image](https://user-images.githubusercontent.com/46320202/86910285-be57f500-c119-11ea-8df9-97bc869b80f8.png)

**Comment by ashraffouda** [comment]
`j.data.zipfile` doesn't exists
