### ISSUE TITLE
redis config storage

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#70]
implement redis storage as alternative to filesystem storage and how to configure/use?

**Comment by abom** [comment]
Use redis store as default? would be a hard dependency for jsng.

**Comment by abom** [comment]
Added as an optional storage (change store="redis" on config.toml to use it).

**Comment by RafyAmgadBenjamin** [comment]
I am verifying this

**Comment by RafyAmgadBenjamin** [comment]
#### verified 
#### Commit Id e98254c4a0a9b904058b2189b7efb5c860651228
1- Go to config file
`'/home/rafy/.config/jumpscale/config.toml'`
2- change the store to be redis
![image](https://user-images.githubusercontent.com/46320202/86254848-bb5b8280-bbb6-11ea-908d-cb3131d5e69b.png)
3-open my sdk project 
```
poetry shell
jsng
```
4- started threebot server
```
j.servers.threebot.start_default
```
5- dumped the keys from Redis which is running on port `6379`
![image](https://user-images.githubusercontent.com/46320202/86255400-594f4d00-bbb7-11ea-8951-3e40847405e8.png)
