### ISSUE TITLE
encrypt only secret fields

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#71]
instead of encrypting the whole config we should encrypt keys that ends? or starts? with `_` maybe we can have `SecretField` type?

**Comment by abom** [comment]
Added `fields.Secret`. (see #68).

**Comment by RafyAmgadBenjamin** [comment]
### verified
#### created Digital Ocean client which has token property defined as secret
``` python
ssh = j.clients.sshkey.get(name= "testing_enc") 
ssh.private_key_path = "/home/rafy/.ssh/id_rsa" 
ssh.load_from_file_system() 
dg = j.clients.digitalocean.get("testDG_enc") 
dg.token = "f4f2bea............."
dg.save()
```
#### checked Configuration path
```
/home/rafy/.config/jumpscale/secureconfig/jumpscale/clients/digitalocean/digitalocean/DigitalOcean/testDG_enc
```
The token were encrypted 
![image](https://user-images.githubusercontent.com/46320202/86113815-06e43280-baca-11ea-99d9-d96f091f6471.png)
