### ISSUE TITLE
Add Gedis

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#85]

**Comment by RafyAmgadBenjamin** [comment]
#### testing scenario
t = j.servers.gedis.get("test") 
t.start()
gedis = j.clients.gedis.get("local") 
gedis.register_actor("greeter", "/home/rafy/sandbox/code/github/threefoldtech/js-ng/jumpscale/servers/gedis/example_actor.py") 
gedis.execute("greeter","add_two_ints",2,3) 
![image](https://user-images.githubusercontent.com/46320202/85720398-b008e280-b6f0-11ea-9546-9eebffb2acb0.png)
