### ISSUE TITLE
gedis client

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#93]
python gedis client
- communicate with gedis server
- introspect the registered actors

**Comment by RafyAmgadBenjamin** [comment]
verified 
### Get Gedis server and start it 
```
t = j.servers.gedis.get("test") 
t.start()     
```
### Get a Gedis Client
```
gedis = j.clients.gedis.get("local")     
```
### Register a new actor
```
gedis.actors.system.register_actor("greeter_test","/home/rafy/sandbox/code/github/threefoldtech/js-ng/jumpscale/servers/gedis/example_actor.py")
```
![image](https://user-images.githubusercontent.com/46320202/85950786-2dd22580-b95f-11ea-86a8-d7456f0bf5af.png)

### Reload the Gedis client to get the new actor that has been loaded
```
gedis.reload() 
```
### Execute the method that has been loaded
```
gedis.actors.greeter_test.add_two_ints(5,10) 
```
![image](https://user-images.githubusercontent.com/46320202/85950809-54905c00-b95f-11ea-8693-5a3b891736ae.png)
