### ISSUE TITLE
replace fs sal with fs2 and fix references

### ISSUE THREAD

**Issue by abom** [js-next/js-ng#94]
In addition to adding docstrings and make sure tests are passing

https://github.com/js-next/js-ng/search?q=j.sal.fs&unscoped_q=j.sal.fs

**Comment by abom** [comment]
Maybe update this PR and merge it too
https://github.com/js-next/js-ng/pull/56/files

**Comment by Pishoy** [comment]
seems we need to remove the file named fs2 in API docs?

![image](https://user-images.githubusercontent.com/21987477/86010961-671c9b00-ba1c-11ea-9b58-3bb49dca8b57.png)

**Comment by xmonader** [comment]
APIs are autogenerated, will be updated when we merge again
